### ISSUE TITLE
Use system adb if present

### ISSUE THREAD

**Issue by DaRacci** [Meister1593/ADBForwarder#6]
I use NixOS which requires patched binaries due to how it works so the downloaded adb tools at runtime won't work, before attempting to download the tools during runtime why not do a quick check to see if the command is present within the systems path?

**Comment by Meister1593** [comment]
Hello. I've made some changes on separate branch, can you check if it works for you?
https://github.com/alvr-org/ADBForwarder/actions/runs/10396080132 you can find linux artifact here
https://github.com/alvr-org/ADBForwarder/actions/runs/10396080132/artifacts/1813782991 - direct link

**Comment by DaRacci** [comment]
I'll give this a shot tonight thanks

**Comment by DaRacci** [comment]
Yeah its working great now.

**Comment by Meister1593** [comment]
Okay, thanks, i will merge it into main and include into next release

**Comment by Meister1593** [comment]
Closed via #7
